# https://docs.docker.com/docker-hub/builds/automated-testing/
version: '2.1'
services:
  redis:
    image: redis

  sut:
    build: .
    tmpfs:
      - /ramdisk:size=1G
    links:
      - redis:redis
    environment:
      REDIS_URL: redis://redis
    command: bundle exec rspec --fail-fast
