source 'https://rubygems.org'

gem 'aws-sdk-s3', '~> 1.0'
gem 'bindata', '~> 2.4'
gem 'concurrent-ruby', '~> 1.1'
gem 'connection_pool', '~> 2.2'
gem 'openssl', '~> 2.1'
gem 'powerpack', '~> 0.1'
gem 'redis', '~> 4.1'
gem 'yaml_extend', '~> 0.2'
gem 'zlib', '~> 1.0'

group 'development' do
  gem 'rspec', '~> 3.8'
  gem 'rubocop', '~> 0.63.0'
  gem 'simplecov', '~> 0.16'
end
