source 'https://rubygems.org'

gem 'aws-sdk-s3', '~> 1.0'
gem 'base64', '~> 0.2'
gem 'bindata', '~> 2.4'
gem 'concurrent-ruby', '~> 1.1'
gem 'logger', '~> 1.6'
gem 'connection_pool', '~> 2.2'
gem 'openssl', '~> 3.1'
gem 'ostruct', '~> 0.6'
gem 'ox', '~> 2.0' # Dependency of aws-sdk-s3 on Ruby 3
gem 'powerpack', '~> 0.1'
gem 'redis', '~> 5.0'
gem 'yaml_extend', '~> 1.3'
gem 'zlib', '~> 3.0'

group 'development' do
  gem 'rspec', '~> 3.8'
  gem 'rubocop', '~> 0.63.0'
  gem 'simplecov', '~> 0.16'
end
